#
# The time span that a player is banned when he/she has died
bannedFromServerTimeSpan: 72h

eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1

commands:

messages:

  #
  # Parameters: <banned time span> (%s)
  BannedUntil: Due to dying in the hardcore world, you have now been banned from this world for %s.

  #
  # Parameters: <player name>(%s) <time span left> (%s)
  StillBanned: Player %s is banned %s.

  #
  # Parameters: <player name> (%s) <time span> (%s)
  PlayerBannedNow: Player %s has now been banned from the hardcore world for %s.

  #
  # Parameters: <player name> (%s)
  PlayerUnbannedNow: Player %s has been unbanned from the hardcore world.

  #
  # Parameters: <player name> (%s)
  PlayerIsNotBanned: Player %s is not banned in the hardcore world.
