#
# The name of the hardcore world
HardcoreWorldName: W_Hardcore
#
# The number of hours that a player is banned when he/she has died in the hardcore world
BannedFromWorldHours: 1

commands:

  #
  # Parameters: -
  TeleportToSpawn: /spawn

messages:

  #
  # Parameters: <banned for hours> (%d)
  BannedUntil: Due to dying in the hardcore world, you have now been banned from this world for %d hours.

  #
  # Parameters: <hours left> (%d), <minutes left> (%d)
  StillBannedHours: Due to your earlier death in the hardcore world, you are banned for another %d hours and %d minutes.

  #
  # Parameters: <minutes left> (%d)
  StillBannedMinutes: Due to your earlier death in the hardcore world, you are banned for another %d minutes more.



