#
# The name of the hardcore world
HardcoreWorldName: W_Hardcore
#
# The number of hours that a player is banned when he/she has died in the hardcore world
BannedFromWorldHours: 1

#
# Debug level
#	0 = NONE (no debug messages)
#	1 = MAJOR (only major messages)
#	2 = MINOR (also minor messages)
#	3 = VERBOSE (all messages)
#
EithonDebugLevel: 1

commands:

  #
  # Parameters: -
  TeleportToSpawn: spawn

messages:

  #
  # Parameters: <banned for hours> (%d)
  BannedUntil: Due to dying in the hardcore world, you have now been banned from this world for %d hours.

  #
  # Parameters: <hours left> (%d), <minutes left> (%d)
  StillBannedHours: Due to your earlier death in the hardcore world, you are banned for another %d hours and %d minutes.

  #
  # Parameters: <minutes left> (%d)
  StillBannedMinutes: Due to your earlier death in the hardcore world, you are banned for another %d minutes more.

  #
  # Parameters: <player name> (%s) <hours> (%d)
  PlayerBannedNow: Player %s has now been banned from the hardcore world for %d hours.

  #
  # Parameters: <player name> (%s)
  PlayerUnbannedNow: Player %s has been unbanned from the hardcore world.

  #
  # Parameters: <player name> (%s)
  PlayerIsNotBanned: Player %s is not banned in the hardcore world.

