name: EithonHardcore
main: net.eithon.plugin.hardcore.Plugin
version: 1.1.1
author: vanbrayne
description: A Minecraft plugin for hard core world additions
depend: [EithonLibrary]
commands:
  ehardcore:
    description: Handle special stuff for the hardcore world
    usage: /ehardcore ban | unban | list
    permission-message: You don't have <permission>
permissions:
  ehardcore.*:
    description: Gives access to all hardcore commands
    default: op
    ehardcore.ban: true
    ehardcore.unban: true
    ehardcore.list: true
  ehardcore.ban:
    description: Access to /ehardcore ban command
    default: op
  ehardcore.unban:
    description: Access to /ehardcore unban command
    default: op
  ehardcore.list:
    description: Access to /ehardcore list command
    default: op
