name: EithonHardcore
main: net.eithon.plugin.hardcore.Plugin
version: ${project.version}
author: vanbrayne
description: A Minecraft plugin for hard core server additions
depend: [EithonLibrary]
softdepend: [EithonBungee]
